version: "3.5"

services:
  database:
    image: postgres:13-alpine
    ports:
      - "54321:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./init-database.sql:/docker-entrypoint-initdb.d/init-database.sql
      - pg_data:/var/lib/postgresql/data
  redis:
    image: redis
    ports:
      - "6379:6379"

volumes:
  pg_data:
