name: Compile and test and deploy stg

on:
  push:
    branches:
      - main

jobs:
  compile_and_test:
    name: Compile and test
    uses: elpassion/flounder/.github/workflows/compile-and-test.yml@main
    secrets: inherit

  deploy_stg:
    name: Deploy staging
    needs:
      - compile_and_test
    if: needs.compile_and_test.result == 'success'
    uses: elpassion/flounder/.github/workflows/deploy-stg.yml@main
    with:
      stage: stg
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  deploy_mobile:
    name: Deploy mobile
    needs:
      - compile_and_test
    if: needs.compile_and_test.result == 'success' && needs.compile_and_test.outputs.mobile_affected == 'mobile'
    uses: elpassion/flounder/.github/workflows/deploy-mobile.yml@main
    secrets: inherit

  test_visual_regression:
    name: Test visual regression
    needs:
      - compile_and_test
    if: needs.compile_and_test.outputs.trigger_vrt
    uses: elpassion/flounder/.github/workflows/test-visual-regression.yml@main
    secrets: inherit

  publish:
    name: Publish package
    needs: [compile_and_test, deploy_stg, deploy_mobile]
    if: |
      always() &&
      needs.compile_and_test.result == 'success' &&
      needs.deploy_stg.result == 'success' &&
      (needs.deploy_mobile.result == 'success' || needs.deploy_mobile.result == 'skipped')
    uses: elpassion/flounder/.github/workflows/publish.yml@main
