name: Compile and test and deploy prod

on:
  push:
    tags:
      - v*

jobs:
  compile_and_test:
    name: Compile and test
    uses: elpassion/flounder/.github/workflows/compile-and-test.yml@main
    secrets: inherit

  deploy_prod:
    name: Deploy production
    needs:
      - compile_and_test
    if: needs.compile_and_test.result == 'success'
    uses: elpassion/flounder/.github/workflows/deploy-prod.yml@main
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

