name: 'Test visual regression'

on:
  workflow_call:

jobs:
  visual-test-loki:
    name: 'Loki'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: nrwl/nx-set-shas@v2

      - uses: pnpm/action-setup@v2.0.1
        name: Install pnpm
        id: pnpm-install
        with:
          run_install: false
          version: 7

      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'pnpm'
          cache-dependency-path: '**/pnpm-lock.yaml'

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}

      - run: pnpm install --frozen-lockfile

      - name: Run loki
        run: pnpm nx run-many --target=loki-test

      - name: Archive screenshots
        if: failure()
        uses: actions/upload-artifact@v1
        with:
          name: loki-screenshots
          path: .loki

      - name: Approve new baselines
        if: failure()
        run: pnpm nx run-many --target=loki-approve

      - name: Create pull request with new baselines
        if: failure()
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update loki baselines
          delete-branch: true
          branch: 'loki-update/${{ github.ref_name }}'
          title: 'VRT Reference images update - ${{ github.ref_name }}'
          body: Automated baseline update PR created by Loki
          reviewers: ${{ github.actor }}
