name: Compile and test

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_call:

jobs:
  compile-and-test:
    concurrency:
      group: "compile-and-test"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./code
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: nrwl/nx-set-shas@v2

      - uses: pnpm/action-setup@v2.0.1
        name: Install pnpm
        id: pnpm-install
        with:
          run_install: false
          version: 7
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "pnpm"
          cache-dependency-path: "**/pnpm-lock.yaml"
      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}

      - run: pnpm install --frozen-lockfile
      - run: npm run ci:lint
      - run: npm run ci:compile
        if: always()
      - run: npm run ci:test
        env:
          NODE_ENV: test
          API_PORT: 3001
          API_ALLOWED_ORIGINS: http://localhost:3000,http://localhost:5000,http://localhost:3002
        if: always()

