module.exports = {
  excludeFromRendering: [
    '*.png',
    '*.jpg',
    '*.jpeg',
    '*.gif',
    '*.svg',
    '*.ico',
  ],
  excludeFromCopying: [
    '.git/',
    '.idea/',
    '.scannerwork/',
    'template-setup/',
    'dist/',
    'tmp/',
    'coverage/',
    '.next/',
    'node_modules/',
    'frontend/node_modules/',
    'backend/node_modules/',
    'admin/node_modules/',
    'mobile/node_modules/',
    'mobile/ios/Pods/',
    'mobile/ios/build/',
    'mobile/ios/Mobile.xcworkspace/xcuserdata/',
    'mobile/ios/fastlane/.env',
    'mobile/android/.gradle/',
    'mobile/android/app/build/',
    'mobile/android/app/*.keystore',
    'mobile/android/fastlane/.env',
    'mobile/android/gradle/wrapper/gradle-wrapper.jar',
    'frontend/.env',
    'backend/.env',
    'admin/.env',
    'atlantis.yaml',
    'workflows/publish.yml',
    '*.env.local',
    '*.env.development.encrypted'
  ],
  template: {
    packages: {
      mobile: 'mobile',
      admin: 'admin',
      backend: 'backend',
      frontend: 'frontend',
    },
    defaultValues: {
      awsRegion: 'eu-west-1',
    },
    placeholderValues: {
      packages: 'backend,frontend,admin',
      aws_region: 'eu-west-1',
      client: 'xxx-client',
      namespace: 'xxx-namespace',
      project: 'xxx-project',
      app_name: ['flounder', 'Flounder', 'FLOUNDER'],
      aws_repo_name: 'flounder-stg-xxx',
    },
  },
};
