name: Deploy storybook to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/design-system
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: pnpm install
      - run: pnpm run deploy-storybook -- --ci
        env:
          GH_TOKEN: ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}
